// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations do not go through the driver adapter — Prisma's own engine
    // connects, and it needs a session it can hold advisory locks on. A
    // transaction pooler hands out a different backend per statement and the
    // lock is lost, so `DIRECT_URL` points at a session-mode connection while
    // `DATABASE_URL` stays on the pooler for the app itself. Locally there is
    // only one database, hence the fallback.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
    // An empty string is not the same as "unset" here — Prisma rejects it, so
    // a blank .env value (the norm once db:deploy is the only thing run) has
    // to be normalized to undefined.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] || undefined,
  },
});
